# Generated by Django 5.0.1 on 2024-02-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text=" The image url",
                        max_length=1000,
                    ),
                ),
                (
                    "prompt",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text=" The prompt used to generate the image",
                        max_length=1000,
                    ),
                ),
                (
                    "date_of_generation",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time the image was generated",
                    ),
                ),
                (
                    "height",
                    models.IntegerField(
                        blank=True, default=0, help_text="The height of the image"
                    ),
                ),
                (
                    "width",
                    models.IntegerField(
                        blank=True, default=0, help_text="The width of the image"
                    ),
                ),
            ],
        ),
    ]
