version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      # Must not be the same as the docker host port
      # <Port exposed> : <Port to redirect to>
      - '5555:5432'
volumes:
  postgres: