services:
  cogito:
    build: 
      context: .
      dockerfile: Dockerfile
    command: gunicorn cogito.wsgi:application --bind 0.0.0.0:8000 --workers 1 --timeout 120
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      DEBUG: "${DEBUG}"
      EMAIL_HOST_USER: "${EMAIL_HOST_USER}"
      EMAIL_HOST_PASSWORD: "${EMAIL_HOST_PASSWORD}"
      DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY}"
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: cogitodb
      DATABASE_USER: cogitouser
      DATABASE_PASSWORD: cogitopassword
    restart: always

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cogitodb
      POSTGRES_USER: cogitouser
      POSTGRES_PASSWORD: cogitopassword
    restart: always

volumes:
  postgres_data:
