# Generated by Django 5.0.1 on 2024-01-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_application', models.DateTimeField(auto_now=True, help_text='The day the application was sent')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='github',
            field=models.URLField(blank=True, default='', verbose_name='GitHub'),
        ),
    ]
