# Generated by Django 5.0.1 on 2025-01-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_alter_memberapplication_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberapplication',
            name='email',
        ),
    ]
