# Generated by Django 3.2.7 on 2023-07-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('name', models.CharField(blank=True, default='', max_length=30, verbose_name='MemberName')),
                ('title', models.CharField(blank=True, default='', max_length=30, verbose_name='MemberTitle')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='MemberImage')),
                ('category', models.CharField(blank=True, default='', max_length=30, verbose_name='MemberCategory')),
                ('email', models.EmailField(max_length=30, primary_key=True, serialize=False, verbose_name='MemberEmail')),
                ('linkedIn', models.URLField(verbose_name='MemberLinkedIn')),
            ],
        ),
    ]
