# Generated by Django 3.2.7 on 2023-07-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='order',
            field=models.IntegerField(blank=True, default=0, max_length=2, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='member',
            name='category',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=50, primary_key=True, serialize=False, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='member',
            name='linkedIn',
            field=models.URLField(verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='title',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Title'),
        ),
    ]
