# Generated by Django 3.2.7 on 2023-07-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20230725_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='order',
            field=models.IntegerField(blank=True, default=0, max_length=2, primary_key=True, serialize=False, verbose_name='Order'),
        ),
    ]
