name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on:
      group: OpenStack
      labels: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Create .env file
        run: |
          echo "EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}" > .env
          echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> .env
          echo "LOG_LEVEL=${{ secrets.LOG_LEVEL || 'INFO' }}" >> .env
          echo "DEBUG=True" >> .env
      
      - name: Run Docker Container
        run: |
          # Do database backup before deploying
          source scripts/backup-database.sh "${{ secrets.BLOB_CREDENTIALS }}"
          docker compose -f prod.compose.yml build
          docker compose -f prod.compose.yml run cogito python manage.py migrate
          docker compose -f prod.compose.yml up -d