name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: CogitoRunner
    steps:
      - name: Create .env file
        run: |
          echo ${{ secrets.DJANGO_SECRET_KEY }}\n${{ secrets.EMAIL_HOST_USER }}\n${{ secrets.EMAIL_HOST_PASSWORD }}\n${{ secrets.LOG_LEVEL }} > .env
      - name: Run Docker Container
        run: |
          sudo docker-compose build
          sudo docker-compose up -d