name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Create .env file
        run: |
          echo "EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}" > .env
          echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> .env
          echo "LOG_LEVEL=${{ secrets.LOG_LEVEL }}" >> .env
      - name: Run Docker Container
        run: |
          sudo docker compose build
          sudo docker compose up -d