name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Create .env file
        run: |
          echo "${{ secrets.DJANGO_SECRET_KEY }}" > .env
          echo "${{ secrets.EMAIL_HOST_USER }}" >> .env
          echo "${{ secrets.EMAIL_HOST_PASSWORD }}" >> .env
          echo "${{ secrets.LOG_LEVEL }}" >> .env
      - name: Run Docker Container
        run: |
          sudo docker-compose build
          sudo docker-compose up -d