name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: sudo docker pull CogitoNTNU/cogito-backend:latest
      - name: Delete Old docker container
        run: sudo docker rm -f cogito-backend || true
      - name: Run Docker Container
        run: |
          sudo docker-compose build
          sudo docker-compose up -d
