name: CI Pipeline

on:
  push:
    branches: ["main", "development"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      debug: True

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Build Docker image
        run: docker compose build

      - name: Run migrations
        run: |
          docker compose run --rm cogito python manage.py makemigrations
          docker compose run --rm cogito python manage.py migrate

      - name: Run tests
        run: docker compose run --rm cogito python manage.py test


  dependabot:
    permissions:
      pull-requests: write
      contents: write

    name: 'Dependabot'
    needs: [build-and-test]
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request'}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
