name: CI Pipeline

on:
  push:
    branches: ["main", "development"]
  pull_request:
    branches: ["main", "development"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image and run tests
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DEBUG: "True"
        run: |
          docker compose build
          docker compose run cogito python manage.py makemigrations
          docker compose run cogito python manage.py migrate
          docker compose up -d
          docker compose run cogito python manage.py test
          docker compose down

  push-to-container-registry:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Backend Image
        run: |
          docker build -t ghcr.io/cogitontnu/web-backend:latest -f ./Dockerfile .
          docker push ghcr.io/cogitontnu/web-backend:latest
