name: Django CI

on:
  push:
    branches: ["main", "development"]
  pull_request:
    branches: ["main", "development"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image and run tests
        run: |
          docker compose build
          docker compose run cogito python manage.py makemigrations
          docker compose run cogito python manage.py migrate
          docker compose up -d
          docker compose run cogito python manage.py test
          docker compose down
