name: Scheduled Workflow

on:
  schedule:
           # ┌───────────── minute (0 - 59)
           # │ ┌───────────── hour (0 - 23)
           # │ │ ┌───────────── day of the month (1 - 31)
           # │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
           # │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
           # │ │ │ │ │
           # │ │ │ │ │
           # │ │ │ │ │
           # * * * * *
    - cron: '23 * * * *'

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # Add more steps as needed
      # ping api endpoint http://www.cogito-backend.net/api/health-check/
      - name: Ping API endpoint
        run: |
          response=$(curl -o /dev/null -s -w "%{http_code}\n" http://www.cogito-backend.net/api/health-check/)
          if [ "$response" -ne 200 ]; then
            echo "API response is not 200, actual response: $response"
            exit 1
          fi
          echo "API response is 200, actual response: $response"